### PR TITLE
Make headers imported in umbrella header public

### PR DESCRIPTION
**Pull request by klaaspieter**
Including TrustKit in Xcode 9 beta 3 in a Swift 4 project wasn't working
because `TrustKit-umbrella.h` wasn't listed as a public header.

After resolving that problem Xcode complained about
`TSTrustKitConfig.h` and `TSKTrustDecision.h`. Making those public as
well fixes support for Xcode 9.

### CODE REVIEW

**Comment by klaaspieter** [comment]
I'm not sure at this point if the `TrustKit-umbrella.h` is still beneficial. It looks like CocoaPods is using `TrustKit.h`. Perhaps this should be simplifying to that as well? I'm going to leave this as is for now because I'm not sure if there is a benefit to the custom umbrella header. If there isn't I'll update the PR appropriately.

**Comment by nabla-c0d3** [comment]
Yeah the umbrella header does seem to be redundant - I think we should get rid of it if Swift does not require it?

**Comment by klaaspieter** [comment]
I'm pretty sure Xcode will automatically do the right thing when it's not explicitly specified. I'll take a look and update the PR.

**Comment by klaaspieter** [comment]
@nabla-c0d3 I updated the PR. Umbrella header and module map are removed now. Builds fine for me in Xcode 8 and Xcode 9 beta 3.

**Comment by nabla-c0d3** [comment]
Thanks!

**Comment by klaaspieter** [comment]
Mind cutting a 1.5.1 release so I don't have to use master?

**Pull request merged**
