### PR TITLE
do not throw if pins or algorithm is missing when pinning is disabled

### LINKED ISSUE #88: Disable pinning for specific subdomains?
Hey,
I want to enable pinning for all our domain, but disable it for a specific subdomain. So I tried it with something like that:
````swift
let trustConfig: [String : Any] = [
            kTSKSwizzleNetworkDelegates:true,
            kTSKPinnedDomains: [
                "mydomain.com" :[
                    kTSKEnforcePinning: true,
                    kTSKPublicKeyAlgorithms: [kTSKAlgorithmRsa2048],
                    kTSKPublicKeyHashes:
                        [],
                    kTSKIncludeSubdomains: true
                ],
                "dontpin.mydomain.com" :[
                    kTSKEnforcePinning: false,
                    kTSKPublicKeyAlgorithms: [kTSKAlgorithmRsa2048],
                    kTSKPublicKeyHashes:
                        []
                ]

            ]
        ]

````
Is this the only way? I had to set `kTSKPublicKeyAlgorithms` and `kTSKPublicKeyHashes' although I want to disable pinning as they mandatory.

Thanks,
Omer

### PR DESCRIPTION
**Pull request by omerlh**
I want to resolve #88

### CODE REVIEW

**Comment by omerlh** [comment]
I think this is a good suggestion - but maybe my solution is simpler? Also, please notice it will allow you not to set the pin hash only if you explicitly set `kTSKEnforcePinning` to false, and I think this is enough. Also, I wasn't aware that the TrustKit configuration can be hierarchical - maybe we should emphasize that in the documentation. In Android I did something like that - and I think your proposal is closer to that, which is a huge benefit:
````xml
<domain includeSubdomains="true">maindomain.com</domain>
    <pin-set>
         ....
    </pin-set>
    <!-- TrustKit Android API -->
    <!-- Do not enforce pinning validation -->
    <trustkit-config enforcePinning="true" disableDefaultReportUri="true">
      <!-- Add a reporting URL for pin validation reports-->
      <report-uri>https://report-uri</report-uri>
    </trustkit-config>
    <domain-config>
      <domain>unsecure.maindomain.com</domain>
      <trustkit-config enforcePinning="false" disableDefaultReportUri="true">
        <!-- Add a reporting URL for pin validation reports-->
        <report-uri>https://report-uri</report-uri>
      </trustkit-config>
    </domain-config>
  </domain-config>
````
So, to conclude - I think maybe comining the options will be the simpliest - something like that:
````objc
kTSKPinnedDomains : @{
       @"www.good.com" : @{
              kTSKPublicKeyAlgorithms : @[kTSKAlgorithmRsa4096],
              kTSKPublicKeyHashes : @[@"TQEtdMbmwFgYUifM4LDF+xgEtd0z69mPGmkp014d6ZY=",
                                        @"TQEtdMbmwFgYUifM4LDF+xgEtd0z69mPGmkp014d6ZY=",
             kTSKPinnedDomains: : @{
                       @"unsecure.good.com" : @{
                                   kTSKEnforcePinning: @FALSE
                                                                 }
                                                         }
                                                                                         ]}}}
````
What do you think?

**Comment by nabla-c0d3** [comment]
Thanks for looking into this. I still think your configuration example is a bit ambiguous:
* When reading it, to me it means that pinning should not be enforced for the subdomain (but the same pins should be used).
* What it actually does is completely disable pinning ; I think `kTSKEnforcePinning` is confusing in this case, because there is no pinning going at all (hence nothing to enforce / not enforce). it is true that it's closer to how Android does it but the Android policy does a whole lot more than pinning which is why it needs to be more complex.

That's why I still think a `kTSKExcludeSubdomainFromParentPolicy` is easier to understand and its behavior is less likely to surprise developers. Does that make sense?

**Comment by omerlh** [comment]
Yes, that make sense. The only question is what make developers less confused - same behavior for android and ios (e.g. if you did one of them, you can use the same for the other) - or more explicit configuration. I am still thinking that unified behavior for android and ios is better, but I think the final decision should be yours :) So I am going to make the necessary changes.

**Comment by omerlh** [comment]
@nabla-c0d3 Tried to implement it with `kTSKExcludeSubdomainFromParentPolicy`.

**Comment by nabla-c0d3** [comment]
Thanks a lot! Quick change: can you rename DomainUtils.h/.c to domain_utils.h/c (to keep consistency in the name) ? I will then merge the PR and add a few extra checks too.
Thanks!

**Comment by omerlh** [comment]
Done. Thank you!

**Pull request merged**
