### PR TITLE
Fix for Trustkit not building on Xcode 14.3 #298

### PR DESCRIPTION
**Pull request by pawisoon**
Fix for Trustkit not building on Xcode 14.3 #298 
Proposed by @Sjenk

### CODE REVIEW

**Comment by pawisoon** [comment]
ping @aj-dt

**Comment by aj-dt** [comment]
Looks good to me. @nabla-c0d3 should we merge?

**Comment by pawisoon** [comment]
@aj-dt @nabla-c0d3 thanks for merging! Can we trigger a new release or re-release of 3.0.1? It would be great :)

**Comment by pawisoon** [comment]
@aj-dt @nabla-c0d3 ping

**Comment by aj-dt** [comment]
Hi @pawisoon 
A new release is coming to github repositories near you in the next few days. Stay tuned.

**Pull request merged**
