### PR TITLE
Support custom reporting class in configuration

### PR DESCRIPTION
**Pull request by Jakenberg**
Hello! First and foremost, thank you very much for making this excellent library.

In this PR, we propose a new feature: custom pin failure reporting.

# Use Case

Our reporting server is strict about the JSON format it will receive. It cannot be updated by us because it's a 3rd-party service (i.e. Airbrake). Using this PR, we are able to customize the format that will be sent to our reporting URI, thus conforming to what our 3rd-party service expects.

# Implementation

- Define new configuration key: `kTSKPinFailureReportClassName`.
- When custom reporting class is used, throw an exception _unless_ it inherits from `TSKPinFailureReport`.
- When no custom reporting class is used, default to using original `TSKPinFailureReport`.
- Write a test confirming the intended usage behavior for `kTSKPinFailureReportClassName`.
- Add "Custom Pin Failure Reporting" section in `docs/getting-started.md`.

God speed 🖖

### CODE REVIEW

**Comment by adamkaplan** [comment]
Why would this need to be configured on a per-domain basis? The functionality (report customization) is a great idea, but it could be easily provided programmatically rather than by reflection.

What if you adjusted this solution as follows:
1. Expose the failure reporter (`TSKBackgroundReporter`) as a `readonly` property on `TSKTrustKit` instances
2. Expose a property on `TSKBackgroundReporter` to set the failure reporter class
`@property (nonatomic, null_resettable) Class failureReportClass; /* set to nil for default class */`
3. Change to use `[self.failureReportClass alloc] ...]` instead, here:
https://github.com/datatheorem/TrustKit/blob/master/TrustKit/Reporting/TSKBackgroundReporter.m#L151

Even better would be changing `TSKPinFailureReport` to generate JSON reports via class method without new allocation each time... that would let you pass an actual instance instead of `Class`. The only method used is `[.. json]` so it could possibly just generate JSON without a new object each time.

**Comment by nabla-c0d3** [comment]
Hello and thanks for looking into this!

There is already a mechanism for customizing things such as the reporting mechanism: https://datatheorem.github.io/TrustKit/documentation/Setting%20up%20a%20Validation%20Callback.html#/c:TSKPinningValidatorCallback.h@T@TSKPinningValidatorCallback

To be honest, I'd rather avoid adding yet another configuration key and more complexity; the callback feature should give you all the flexibility you need. Any specific reason for not using it?

Thanks!

**Comment by adamkaplan** [comment]
The issue is that the validation callback doesn’t allow in-band customization of the report without taking on ownership of the entire reporting flow, network calls, throttling, etc. at least as far as I can tell.

While I agree with you that configuration isn’t a good fit, his case for a deeper hook into the report payload generation is legitimate and interesting.

**Comment by Jakenberg** [comment]
@adamkaplan:

> Why would this need to be configured on a per-domain basis?

This PR doesn't actually allow this. `TSKPinFailureReportClassName` is declared as a top-level key; higher-order than `TSKPinnedDomains`.

>  ...it could be easily provided programmatically rather than by reflection.

Indeed. We went with this approach initially, but realized it wasn't compatible with the ideology of configuring TrustKit from a plist file. Frankly, we are neutral on either approach.

> ...generate JSON reports via class method without new allocation each time... that would let you pass an actual instance instead of Class.

We disagree. In `TSKPinFailureReport`, only the `json` method is called, but it's still useful as a vehicle of data (i.e. bundle ID, app version, etc) to be passed/read from by other objects ([example](https://github.com/datatheorem/TrustKit/blob/master/TrustKit/Reporting/TSKReportsRateLimiter.m#L44)).

-----------

@nabla-c0d3:

@adamkaplan is right about all-or-nothing customization. We wanted to keep all of the battle-tested reporting functionality that's already there while simply customizing the format of the JSON payload sent to our reporting URLs.

> ...avoid adding yet another configuration key and more complexity...

This isn't a required customization key. In fact, there's no mention of `TSKPinFailureReportClassName` excluding the excerpt we wrote for it in the docs. For this reason we do not believe this adds any unnecessary complexity for the implementor unless they intentionally seek it out.

> ...the callback feature should give you all the flexibility you need.

We could update the callback, but we found some limitations:

- [`sendValidationReport:` is called on a different thread than `pinningValidatorCallback`](https://github.com/datatheorem/TrustKit/blob/master/TrustKit/TrustKit.m#L178-L188).
- `pinningValidatorCallback` would need to be extended. For example, it's return value could be any instance of `TSKPinFailureReportClass`, which is then used in `sendValidationReport`.

There is likely more to it than this, but these two raise an interesting point. Primarily due to the second point being a breaking change, we don't believe this would be a better approach than what we've done in this PR.

-----------

After a week of using this PR, we have had excellent results. We wouldn't be utilizing the full capability of this library without it so we intend to continue using it. However, it's obviously up to you whether or not you believe we are the only implementors of this library out there that want customization _only_ for their failure report schema. We think it's highly unlikely that we're the only ones ;) 

Thank you for taking time out to discuss this PR with us!

**Comment by adamkaplan** [comment]
>...generate JSON reports via class method without new allocation each time... that would let you pass an actual instance instead of Class.
>We disagree. In TSKPinFailureReport, only the json method is called, but it's still useful as a vehicle of data (i.e. bundle ID, app version, etc) to be passed/read from by other objects (example).

You're right, good catch. A static approach to that class isn't right. I still believe a programatic approach is ideal - perhaps with basic inheritance though.

Definitely awesome to contribute this functionality. Just working out the details here. I've contributed quite a few features to this library that I thought were only valid for my companies weird use cases to later to find issues filed against them (meaning others found it useful too! wonderful!).

**Comment by sbycrosz** [comment]
Any chance this will get merged? We would want to report SSL errors to slack

**Comment by nabla-c0d3** [comment]
@sbycrosz You don't need this PR to push SSL errors to Slack. If you set up an endpoint to receive the pinning failure reports and to then forward them to Slack, you should be good to go; you don't want to embed a Slack webhook URL into your app.

**Comment by adamkaplan** [comment]
> @sbycrosz You don't need this PR to push SSL errors to Slack. If you set up an endpoint to receive the pinning failure reports and to then forward them to Slack, you should be good to go; you don't want to embed a Slack webhook URL into your app.

That's a good point, though I wouldn't assume that the Slack secrets/webhook are embedded in the app. Maybe they are, but at my company all apps integrate a robust remote config system that avoids this problem. I think it's reasonable to allow for customized reporting. But, I also agree that the use cases described are best done using a middle-tier report proxy... it's much more secure that way.

This is a tough one. The use case is debatable, but the functionality seems quite reasonable, if not potentially avoidable in most cases.

**Comment by nabla-c0d3** [comment]
I was waiting to see if there would be more users asking for this. I think overall the use case is too specific while adding complexity. Closing this PR now.

**Pull request closed without merging**
