### PR TITLE
Linker issues

### PR DESCRIPTION
**Pull request by adamkaplan**
- [x] Fix missing library in link step for both Obj-C and Swift demo app targets
- [x] Run pod update in demo app

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Thanks!

**Comment by nabla-c0d3** [comment]
@adamkaplan Unrelated to this issue, but my account on Slack does not work anymore and I couldn't find another way to contact you. Were you able to ask around for the request I had? My email address is on my GitHub profile.
Thanks!

**Comment by adamkaplan** [comment]
Let me see about restoring guest access.

**Comment by adamkaplan** [comment]
@nabla-c0d3 We migrated to a new workspace a few months back and the guests were lost. I can re-invite, but due to the security controls it'd be easier to invite me to a TrustKit/Support Slack if you have one. Let me know.. I can make it work either way.

**Comment by nabla-c0d3** [comment]
Sounds good, I created a gitter chat room: https://gitter.im/TrustKit/Lobby

**Pull request merged**
