### PR TITLE
Xcode 9 beta3

### PR DESCRIPTION
**Pull request by wolffan**
This includes the changes for #134 plus removing the Umbrella header.
We also tried and works for our project (MAC app)

### CODE REVIEW

**Comment by adamkaplan** [comment]
This seems to work for me in some limited testing.
I recommend first merging #134 first just so that the contributors credit is preserved 😉

**Comment by nabla-c0d3** [comment]
Thanks!

**Comment by wolffan** [comment]
:)

**Comment by wolffan** [comment]
I'm testing this again and it doesn't seem to work :(
I'll do more digging to see what's broken

**Comment by wolffan** [comment]
The branch I had open did, but not the new release

**Comment by wolffan** [comment]
A because no release has been done with this, my apologies!

**Pull request merged**
